### PR TITLE
Submission for ID1 Challenge

### PR DESCRIPTION
**Pull request by VivekInCloud**
Submission for ID1 & ID4 Challenge

### CODE REVIEW

**Comment by cryptovoyagr** [comment]
Unverified Commit signature for 280e1f4

Unverified Commit signature for 1515630

Unverified Commit signature for ab63b8e

**Comment by supermario** [comment]
rejected:B1
reason:runtime significantly lower than 30 days

**Comment by supermario** [comment]
rejected:B3
reason:missing logs for 3 different startup types

**Comment by supermario** [comment]
confirmed:B6

**Comment by cryptovoyagr** [comment]
confirmed:ID4
AccountAddress:3ENcknL8coACwSSiR1EwXwxWmLjb9d9sURdyuqQK6X39vK67wN
DeviceDetails:verified

**Comment by supermario** [comment]
confirmed:B4
address:3ENcknL8coACwSSiR1EwXwxWmLjb9d9sURdyuqQK6X39vK67wN
baker:278

**Comment by VivekInCloud** [comment]
Form Submitted 4/27 10:00 AM IST

**Pull request closed without merging**
