### PR TITLE
Id4 and ID2

### PR DESCRIPTION
**Pull request by amonxx**

### CODE REVIEW

**Comment by supermario** [comment]
rejected:B1
It looks like you are trying to submit B1, however it seems like the following submission criteria are problematic: 
- Logs are missing
We’ve thus marked B1 as rejected, however if this is a mistake, please upload the log summary and we can re-review.

**Comment by cryptovoyagr** [comment]
pending:ID2
account1:3EZTdPfQM1MWMHt2aJ58Phm1FhtUf3X2bHrntB3dG71D6N4EUn
account2:invalid address

We cannot fully verify this submission. Please assist us in typing out the second account addresses for ID2 in full as text in a comment on this PR. Thank you!
@dogukan59

**Comment by cryptovoyagr** [comment]
rejected:ID4
reason:We cannot fully verify this submission. It looks like you are trying to submit ID4, however, it seems like we cannot find the transaction between your account and Concordium Test Account.

**Comment by cryptovoyagr** [comment]
rejected:ID2
reason:We cannot fully verify this submission. It looks like you are trying to submit ID, however, it seems like address2 does not point to any transaction. Hence, we cannot further verify.

**Comment by dogukan59** [comment]
please reconsider---- 
https://github.com/dogukan59/Testnet3-Challenges/blob/ID4/Identities/ID4/ID4%20Submission

**Comment by cryptovoyagr** [comment]
confirmed:ID4
AccountAddress:3EZTdPfQM1MWMHt2aJ58Phm1FhtUf3X2bHrntB3dG71D6N4EUn
DeviceDetails:verified

**Comment by cryptovoyagr** [comment]
confirmed:ID2
account1:3EZTdPfQM1MWMHt2aJ58Phm1FhtUf3X2bHrntB3dG71D6N4EUn
account2:3EggFTALWvGJ5WdUvLrLA9goakdQW9uixkBNvA8ZTzqku6urzG
PublicDataAttributes:verified
DeviceMake&Model:Verified

**Comment by amonxx** [comment]
form submitted-27/04/2022 (UTC +3) 02:38

**Pull request closed without merging**
