### PR TITLE
Yurbason

### PR DESCRIPTION
**Pull request by Yurbason**
Node name: Yurbason
Node ID: 8b208d47fc31f743
Baker ID: 49 and 650

### CODE REVIEW

**Comment by supermario** [comment]
rejected:B1
reason:runtime significantly lower than 30 days

**Comment by Yurbason** [comment]
> rejected:B1
> reason:runtime significantly lower than 30 days

I had 36 days of uptime at the time of submitting a request to github! I disagree with your findings.
here is the link to the log
https://github.com/Concordium/Testnet3-Challenges/blob/2859ca383971e00c901a0ea6e2e31dbc06e591f3/Bakers/B1/concordium-testnet-system-report.log

**Comment by Yurbason** [comment]
> rejected:B1
> reason:runtime significantly lower than 30 days

https://github.com/Yurbason/Testnet3-Challenges/tree/main/Bakers/B1
please read carefully all the files posted by me

**Comment by supermario** [comment]
Hi @Yurbason 

Your submitted logs only show`runtime:473`, hence the original assessment. However I see in your screenshots it's outlining 1 month. This would normally not be acceptable (as screenshots can be modified) but we'll allow it in this case.

**Comment by supermario** [comment]
confirmed:B1
node: 8b208d47fc31f743

**Comment by Yurbason** [comment]
> Hi @Yurbason
> 
> Your submitted logs only show`runtime:473`, hence the original assessment. However I see in your screenshots it's outlining 1 month. This would normally not be acceptable (as screenshots can be modified) but we'll allow it in this case.

perhaps this happened due to the fact that I did truncation of the logs after completing task B6
sudo truncate -s 0 /var/lib/docker/containers/62ee3560afed270962777083132e403c0d70a6c5ded4454c800f577e678e7ee4/62ee3560afed270962777083132e403c0d70a6c5ded4454c800f577e678e7ee4-json.log

here I indicated that the logs consist of two logs
https://github.com/Yurbason/Testnet3-Challenges/blob/main/Bakers/B1/B1-Yurbason.txt

runtime:473 - from the first log after completing task B6
runtime:0 - from the second log

most likely, after truncating the logs, your collector was unable to collect information correctly
try to do it yourself on the testnet 

https://github.com/Yurbason/Testnet3-Challenges/blob/main/Bakers/B1/screen3.JPG
in this file, I specially posted a screenshot of the fact that the process was launched as early as October 9 and did not turn off until the moment I downloaded the logs for B1

anyway, thank you so much for approving me on this task!

**Comment by cryptovoyagr** [comment]
confirmed:ID1
account1:4iQhRgiQfnpktrLtT58FVaQoX3H7yRcMS1qLqbuigYDkq664fa
account2:4G8JiibcfoVNduJ3ALRkXM9exgp77gXFVifm1nhmB7RRZB2kjC

**Comment by supermario** [comment]
rejected:B2
reason:insufficient number of restarts in logs

**Comment by supermario** [comment]
confirmed:B3

**Comment by supermario** [comment]
confirmed:B6

**Comment by cryptovoyagr** [comment]
confirmed:ID2
account1:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
account2:3Tw6wUcHVaaSCpNMnkmtmJgCyH6SHtabt4UMFufCS8fePhG8We
PublicDataAttributes:Verified
DeviceMake&Model:Verified

**Comment by Yurbason** [comment]
> rejected:B2
> reason:insufficient number of restarts in logs

and I also disagree with this (
what lines in the log need to be found?

from my log file:
Powershell
Select-String -Path D:\del\crc\B2.log -Pattern "Starting out of band catch-up"

77:2020-11-14T21:36:21.661658529Z: INFO: Starting out of band catch-up
964792:2020-11-15T05:26:19.625522180Z: INFO: Starting out of band catch-up
1297204:2020-11-15T08:41:04.456708180Z: INFO: Starting out of band catch-up
4539779:2020-11-16T10:39:58.598997098Z: INFO: Starting out of band catch-up
5506968:2020-11-16T18:58:33.812673858Z: INFO: Starting out of band catch-up
6459035:2020-11-17T03:18:20.381920279Z: INFO: Starting out of band catch-up
7523710:2020-11-17T13:13:45.714610619Z: INFO: Starting out of band catch-up
10018684:2020-11-18T12:17:01.487513856Z: INFO: Starting out of band catch-up
10319628:2020-11-18T15:00:15.643017032Z: INFO: Starting out of band catch-up
11799461:2020-11-19T04:37:03.114873461Z: INFO: Starting out of band catch-up
12349131:2020-11-19T09:37:55.704661870Z: INFO: Starting out of band catch-up
14871330:2020-11-20T07:53:29.398676526Z: INFO: Starting out of band catch-up
15818875:2020-11-20T16:41:33.216245827Z: INFO: Starting out of band catch-up
16889317:2020-11-21T03:20:45.265898173Z: INFO: Starting out of band catch-up
17848670:2020-11-21T12:48:07.670386045Z: INFO: Starting out of band catch-up

every day there was a restart, 2 times, during the week (15, 16, 17, 18, 19, 20, 21 = 7 days total)

**Comment by supermario** [comment]
@Yurbason can you please re-submit your logs with the log summary tool? Are restarts should be evident in the summary logs (this is how we've confirmed them for many other submissions already), however in the summary logs you've submitted, I cannot see any periodic restarts.

**Comment by supermario** [comment]
confirmed:B2

**Comment by cryptovoyagr** [comment]
confirmed:ID3
DocumentType:verified
Nationality:verified
DeviceDetails:verified
Experience:verified
Screenshot:verified

**Comment by supermario** [comment]
confirmed:B3

**Comment by cryptovoyagr** [comment]
pending:ID4
AccountAddress:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
DeviceDetails:verified

We cannot fully verify this submission.It looks like you are trying to submit ID4, however, it seems like we cannot find the transaction between your account and Concordium Test Account. Please assist us by providing the missing credentials.

@Yurbason

**Review by cryptovoyagr — COMMENTED** [review]
pending:T1
account1:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
account2:3Tw6wUcHVaaSCpNMnkmtmJgCyH6SHtabt4UMFufCS8fePhG8We
DeviceDetails:verified
Screenshot:missing

We cannot fully verify this submission. Please provide us with screenshots with all transactions. 
@Yurbason

**Comment by Yurbason** [comment]
> pending:T1
> account1:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
> account2:3Tw6wUcHVaaSCpNMnkmtmJgCyH6SHtabt4UMFufCS8fePhG8We
> DeviceDetails:verified
> Screenshot:missing
> 
> We cannot fully verify this submission. Please provide us with screenshots with all transactions.
> @Yurbason

it is wrong of you to ask for screenshots! There was not a word in the rules about the need to attach a screenshot!
Posted only those screenshots that I managed to get. Unfortunately, the rest of the data is not loaded, the client cannot display transactions that were made before October 29 :( Screenshot is attached.
https://github.com/Yurbason/Testnet3-Challenges/tree/main/Transactions/T1/screenshots

**Comment by Yurbason** [comment]
> pending:ID4
> AccountAddress:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
> DeviceDetails:verified
> 
> We cannot fully verify this submission.It looks like you are trying to submit ID4, however, it seems like we cannot find the transaction between your account and Concordium Test Account. Please assist us by providing the missing credentials.
> 
> @Yurbason

screenshot attached
but I repeat - this was not stipulated in the rules!
How are you going to validate bulk transactions? do I have to take a screenshot for each transaction? (you understand that this is a stupid idea)
https://github.com/Yurbason/Testnet3-Challenges/tree/main/Identities/ID4/screenshots

**Comment by cryptovoyagr** [comment]
confirmed:T1
account1:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
account2:3Tw6wUcHVaaSCpNMnkmtmJgCyH6SHtabt4UMFufCS8fePhG8We
DeviceDetails:verified

**Comment by supermario** [comment]
confirmed:B4
address:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
baker:49

**Comment by cryptovoyagr** [comment]
confirmed:T2
account1:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
account2:3Tw6wUcHVaaSCpNMnkmtmJgCyH6SHtabt4UMFufCS8fePhG8We

**Comment by Yurbason** [comment]
@cryptovoyagr 
pay attention to ID4 - I added a screenshot)
https://github.com/Yurbason/Testnet3-Challenges/tree/main/Identities/ID4/screenshots

**Comment by cryptovoyagr** [comment]
confirmed:T3
address:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw

**Comment by cryptovoyagr** [comment]
confirmed:T4
address:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw

**Comment by cryptovoyagr** [comment]
confirmed:ID4
AccountAddress:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw
DeviceDetails:verified

**Comment by supermario** [comment]
confirmed:B5
address:4oERQtx6aMyo1Wjhp8ZywoyxB2sUA4sFgx8h3j4278ZH2NjHBw

**Comment by Yurbason** [comment]
Form Submitted 8.10pm UTC+3

**Pull request closed without merging**
