### PR TITLE
Challenges - ID1, ID2, ID3, ID4, B1, B2, B3, B4, B5, B6

### PR DESCRIPTION
**Pull request by andrste**
Node id: 5005df6999fb169f
Address: 45bfqjei4fQa981qLji1mxdvi8AMi7nKTqs5VuHAJsqaTdKkUU
Name: AlphaStake

### CODE REVIEW

**Comment by supermario** [comment]
confirmed:B1
node:5005df6999fb169f

**Comment by cryptovoyagr** [comment]
confirmed:ID1
account1:4goBpDc8LLkPWA6i6keUpURJdEDQsXWm9i6kVjaAD4WzeRs6gk
account2:3uB3ewjunCN1qSzTa87XscVsgtzfwGHNirYuaKBw76iaYG8BzQ

**Comment by supermario** [comment]
confirmed:B2

**Comment by supermario** [comment]
confirmed:B3

**Comment by supermario** [comment]
confirmed:B6

**Comment by cryptovoyagr** [comment]
confirmed:ID2
account1:2xUiE9JmG5UWstRsh6gsbPUpjPr1UKLtTtLFW5bMxRB4CWDtEc
account2:4KYWymfuk4yHAMJ4E6nTvtfSkPSNWwHbRECgoai3GSugrsgKsw
PublicDataAttributes:Verified
DeviceMake&Model:Verified

**Comment by cryptovoyagr** [comment]
rejected:ID3
reason:We cannot fully verify this submission. It looks like you are trying to submit ID3, however, it seems like there are no supporting details.

**Comment by andrste** [comment]
> rejected:ID3
> reason:We cannot fully verify this submission. It looks like you are trying to submit ID3, however, it seems like there are no supporting details.

Hi, you have approved my other ID3 from different branch: https://github.com/Concordium/Testnet3-Challenges/pull/242

**Comment by supermario** [comment]
@andrste given it seems you have individual PRs for every submission tagged in this group PR, I'm closing this one to remove the duplicate submissions.

**Comment by andrste** [comment]
> @andrste given it seems you have individual PRs for every submission tagged in this group PR, I'm closing this one to remove the duplicate submissions.

Got it Mario, thanks! Just wanted to be sure that I will be in top 250 on B tasks.

**Pull request closed without merging**
