### PR TITLE
Challanges

### PR DESCRIPTION
**Pull request by donadel01**
Baker ID: 1134

### CODE REVIEW

**Comment by supermario** [comment]
rejected:B1
It looks like you are trying to submit B1, however it seems like the following submission criteria are problematic: 
- Logs are missing
We’ve thus marked B1 as rejected, however if this is a mistake, please upload the log summary and we can re-review.

**Comment by donadel01** [comment]
> rejected:B1
> It looks like you are trying to submit B1, however it seems like the following submission criteria are problematic:
> 
> * Logs are missing
>   We’ve thus marked B1 as rejected, however if this is a mistake, please upload the log summary and we can re-review.

https://github.com/Concordium/Testnet3-Challenges/issues/1250

Some of the logs could not be retrieved due to an error in this link. Other server logs that it worked for 30 days were also uploaded.

[concordium-testnet-node.log](https://github.com/Concordium/Testnet3-Challenges/files/5741961/concordium-testnet-node.log)
[auth.log.3.gz](https://github.com/Concordium/Testnet3-Challenges/files/5741962/auth.log.3.gz)
[auth.log.4.gz](https://github.com/Concordium/Testnet3-Challenges/files/5741963/auth.log.4.gz)


[concordium-testnet-system-report.log](https://github.com/Concordium/Testnet3-Challenges/files/5741958/concordium-testnet-system-report.log)
[concordium-testnet-node-49a1f4b52e705f31a96d3ac7585f11f51de6a4538d142a85a571c414507dcd5d.log](https://github.com/Concordium/Testnet3-Challenges/files/5741959/concordium-testnet-node-49a1f4b52e705f31a96d3ac7585f11f51de6a4538d142a85a571c414507dcd5d.log)
[auth.log.2.gz](https://github.com/Concordium/Testnet3-Challenges/files/5741960/auth.log.2.gz)

**Comment by supermario** [comment]
confirmed:B1
node:04da7a8399c95de4

**Comment by cryptovoyagr** [comment]
confirmed:ID1
account1:4fuAotnDX6FSYQj2WWsHnzWjx1t32o9d6K4Tfu7SXrSgPQe61Z
account2:4Pa4WFcipca5DbXGXmjf6iRgHEYr1suXgQ1zJUawuHQniSY6jE

**Comment by supermario** [comment]
It appears many of your submissions have duplicates which confused us. Given I've found standalone submissions for all the other items I've untagged everything except B3 for review here, and removed prior comments.

**Comment by supermario** [comment]
It appears many of your submissions have duplicates which confused us. Given I've found standalone submissions for all the other items I've untagged everything for review here, and removed prior comments.

**Pull request closed without merging**
