### PR TITLE
(ID3 + ID4) + ( B4 )

### PR DESCRIPTION
**Pull request by 0xhankoc**
The required docs are in the folder.

### CODE REVIEW

**Comment by cryptovoyagr** [comment]
confirmed:ID3
DocumentType:verified
Nationality:verified
DeviceDetails:verified
Experience:verified
Screenshot:verified

**Comment by supermario** [comment]
confirmed:B3

**Comment by cryptovoyagr** [comment]
confirmed:ID4
AccountAddress:3hmpMHmFSYToset4FXtCzpYrBvLjTTA41KHSqwkfmz8Fm51b9q
DeviceDetails:verified

**Comment by supermario** [comment]
rejected:B6
reason:logs are missing

**Comment by supermario** [comment]
confirmed:B4
address:3hmpMHmFSYToset4FXtCzpYrBvLjTTA41KHSqwkfmz8Fm51b9q
baker:740

**Pull request closed without merging**
