### PR TITLE
B1

### PR DESCRIPTION
**Pull request by Fatihk**

### CODE REVIEW

**Comment by supermario** [comment]
rejected:B1
It looks like you are trying to submit B1, however it seems like the following submission criteria are problematic: 
- Logs are missing
We’ve thus marked B1 as rejected, however if this is a mistake, please upload the log summary and we can re-review.

**Comment by cryptovoyagr** [comment]
confirmed:ID2
account1:4V1vBoLNKy8japTmFzwdzy7mvoUor5SHrm6T62FShMnDKVtvpx
account2:4X8sxnwWzi7AUQxm1TdNkmJfk9itizD2yLgWHTSzXMYXk6RGok
PublicDataAttributes:Verified
DeviceMake&Model:Verified

**Comment by cryptovoyagr** [comment]
confirmed:ID3
DocumentType:verified
Nationality:verified
DeviceDetails:verified
Experience:verified
Screenshot:missing

**Comment by cryptovoyagr** [comment]
rejected:ID4
reason:We cannot fully verify this submission. It looks like you are trying to submit ID4, however, it seems like we cannot find the transaction between your account and Concordium Test Account.

**Comment by supermario** [comment]
confirmed:B4
address:4V1vBoLNKy8japTmFzwdzy7mvoUor5SHrm6T62FShMnDKVtvpx
baker:518

**Pull request closed without merging**
