### PR TITLE
 (T1) Use Concordium ID to send and receive GTU

### PR DESCRIPTION
**Pull request by stranger-around-the-world**

### CODE REVIEW

**Review by cryptovoyagr — COMMENTED** [review]
Please provide us with screenshots with all transactions.

**Comment by cryptovoyagr** [comment]
pending:T1
account1:3ypohoxwVNPQY5JcdXFvAsZJktaC4PqVcBndiyq99qmrSBNJKc
account2:3fXby4wPXezD5m1u4GKanE2asLDNBCoAShKd4JBVki4JwrXLfd
DeviceDetails:verified
Screenshot:missing

We cannot fully verify this submission. Please provide us with screenshots with all transactions.
@stranger-around-the-world

**Comment by stranger-around-the-world** [comment]
I disagree with your decision because: the screenshot was not part of the assignment.

**Comment by cryptovoyagr** [comment]
confirmed:T1
account1:3ypohoxwVNPQY5JcdXFvAsZJktaC4PqVcBndiyq99qmrSBNJKc
account2:3fXby4wPXezD5m1u4GKanE2asLDNBCoAShKd4JBVki4JwrXLfd
DeviceDetails:verified

**Pull request closed without merging**
