### PR TITLE
B3 Submission

### PR DESCRIPTION
**Pull request by kaanci**
B3 Submission

Baker Id: 503
37KvPDuQeikH4fC2Gmu5ViBKHLDYddbP3JaGoqpTkQf4eV5Q73

[concordium-testnet-node.log](https://github.com/Concordium/Testnet3-Challenges/files/5391763/concordium-testnet-node.log)
[concordium-testnet-system-report.log](https://github.com/Concordium/Testnet3-Challenges/files/5391764/concordium-testnet-system-report.log)

### CODE REVIEW

**Comment by cryptovoyagr** [comment]
rejected:ID3
reason:We cannot fully verify this submission. It looks like you are trying to submit ID3, however, it seems like there are no supporting details.

**Comment by cryptovoyagr** [comment]
rejected:ID2
reason:We cannot fully verify this submission. It looks like you are trying to submit ID3, however, it seems like there are no supporting details.

**Comment by cryptovoyagr** [comment]
rejected:ID4
reason:We cannot fully verify this submission. It looks like you are trying to submit ID3, however, it seems like there are no supporting details.

**Comment by cryptovoyagr** [comment]
rejected:ID1
reason:We cannot fully verify this submission. It looks like you are trying to submit ID3, however, it seems like there are no supporting details.

**Comment by kaanci** [comment]
Dear Suhas,

For ID1 challenge colud you please look the following link;

https://github.com/kaanci/Testnet3-Challenges/blob/main/Identities/ID1/ID1%20Fake%20Identities

Thanks.

**Comment by kaanci** [comment]
Dear Suhas,

For Challenge ID4, cloud you please look the following link:

https://github.com/kaanci/Testnet3-Challenges/blob/main/Identities/Send%205%20GTU%20QR%20%20Test%20Address

Thanks & Regards

**Comment by kaanci** [comment]
Dear Suhas,

For challenge ID3, could you please look the following links:

https://github.com/kaanci/Testnet3-Challenges/commit/c8e2f315b0eeedec05ce43aae03adc73990d4b21

https://github.com/kaanci/Testnet3-Challenges/pull/10

Thanks.

**Comment by supermario** [comment]
confirmed:B4
address:37KvPDuQeikH4fC2Gmu5ViBKHLDYddbP3JaGoqpTkQf4eV5Q73
baker:389

**Pull request closed without merging**
