### PR TITLE
Id4

### PR DESCRIPTION
**Pull request by akgnsvas**

### CODE REVIEW

**Comment by cryptovoyagr** [comment]
confirmed:ID1
account1:38nzyaNhGFVUHrrdh3aAdAjKA7BUsQosMgv7L7HMmUqEt5MU88
account2:4F9eg4NZyQSkjzNTkN44cRWTWzjASAcyfdANUmMfZvsij214pR

**Comment by cryptovoyagr** [comment]
confirmed:ID2
account1:38nzyaNhGFVUHrrdh3aAdAjKA7BUsQosMgv7L7HMmUqEt5MU88
account2:4F9eg4NZyQSkjzNTkN44cRWTWzjASAcyfdANUmMfZvsij214pR
PublicDataAttributes:Verified
DeviceMake&Model:Verified

**Comment by cryptovoyagr** [comment]
confirmed:ID3
DocumentType:verified
Nationality:verified
DeviceDetails:verified
Experience:verified
Screenshot:verified

**Comment by supermario** [comment]
rejected:B6
reason:logs are missing

**Comment by supermario** [comment]
Closing as duplicate confirmed in #132.

**Pull request closed without merging**
