### PR TITLE
nodeId: c7208f5896ac8fd8 b2 submit

### PR DESCRIPTION
**Pull request by mahofmahof**

### CODE REVIEW

**Review by mahofmahof — COMMENTED** [review]
nodeId: c7208f5896ac8fd8

**Comment by cryptovoyagr** [comment]
confirmed:ID2
account1:4Dp4ghnGKdq1Md5REuYRxnrKb4AjH7VDKQexkrQVX6KR4yFWTZ
account2:3jFkViSBWk6xxtfaRW5xnPbsRXWL91AVC251Ar2AGkGeWPLJGx
PublicDataAttributes:Verified
DeviceMake&Model:Verified

**Comment by cryptovoyagr** [comment]
confirmed:ID3
DocumentType:verified
Nationality:verified
DeviceDetails:verified
Experience:verified
Screenshot:verified

**Comment by cryptovoyagr** [comment]
confirmed:ID4
AccountAddress:3ExNrBuoeacepN2S9f7bPtZqiDXTV9vz8F6TNXebRLoZxb12aP
DeviceDetails:verified

**Comment by mahofmahof** [comment]
They all seem under review what is the problem?

**Comment by cryptovoyagr** [comment]
confirmed:ID1
account1:4Dp4ghnGKdq1Md5REuYRxnrKb4AjH7VDKQexkrQVX6KR4yFWTZ
account2:3jFkViSBWk6xxtfaRW5xnPbsRXWL91AVC251Ar2AGkGeWPLJGx

**Comment by supermario** [comment]
confirmed:B1
node:7b43331d5dd867c5

**Comment by supermario** [comment]
confirmed:B2

**Comment by supermario** [comment]
confirmed:B3

**Comment by supermario** [comment]
confirmed:B4
address:3tsuetTKjhouDYgTgdZPdnWoYXWbzf1Xe2YhZa3Pi1WjakNbxy
baker:721

**Comment by supermario** [comment]
confirmed:B5
address:3tsuetTKjhouDYgTgdZPdnWoYXWbzf1Xe2YhZa3Pi1WjakNbxy

**Comment by supermario** [comment]
confirmed:B6

**Comment by supermario** [comment]
> They all seem under review what is the problem?

@mahofmahof the problem was you closed your PR so it was not reviewed. It's now reviewed.

**Comment by mahofmahof** [comment]
thanks

**Pull request closed without merging**
