### PR TITLE
B4 update

### PR DESCRIPTION
**Pull request by huseyinfe**

### CODE REVIEW

**Comment by cryptovoyagr** [comment]
confirmed:ID1
account1:33dKda6KxEHcPquCcd6ToYeeCDPoBeV4jFj7FPK6Up9QyuqegZ
account2:3w1qLR8yLPvKv6SjvZDWUiNREaz3UgEmGSo9R9tDn1H3hy3EFH

**Comment by cryptovoyagr** [comment]
confirmed:ID2
account1:33dKda6KxEHcPquCcd6ToYeeCDPoBeV4jFj7FPK6Up9QyuqegZ
account2:3w1qLR8yLPvKv6SjvZDWUiNREaz3UgEmGSo9R9tDn1H3hy3EFH
PublicDataAttributes:verified
DeviceMake&Model:verified

**Comment by cryptovoyagr** [comment]
confirmed:ID4
AccountAddress:3w1qLR8yLPvKv6SjvZDWUiNREaz3UgEmGSo9R9tDn1H3hy3EFH
DeviceDetails:verified

**Comment by cryptovoyagr** [comment]
confirmed:ID3
DocumentType:verified
Nationality:verified
DeviceDetails:verified
Experience:verified
Screenshot:verified

**Comment by supermario** [comment]
rejected:B1
It looks like you are trying to submit B1, however it seems like the following submission criteria are problematic: 
- Logs are missing
We’ve thus marked B1 as rejected, however if this is a mistake, please upload the log summary and we can re-review.

**Comment by supermario** [comment]
confirmed:B4
address:3ixS2Vz4kVUgmNetd9aQghNVjQPrL81T8Nabck1TgxWDZjqthV
baker:508

**Comment by supermario** [comment]
confirmed:B4
address:3ixS2Vz4kVUgmNetd9aQghNVjQPrL81T8Nabck1TgxWDZjqthV
baker:508

**Pull request closed without merging**
