### PR TITLE
mrekos testnet3 Challenges 

### PR DESCRIPTION
**Pull request by mrekos**
Id: ed577cc56319131c

### CODE REVIEW

**Comment by supermario** [comment]
rejected:B1
It looks like you are trying to submit B1, however it seems like the following submission criteria are problematic: 
- Logs are missing
We’ve thus marked B1 as rejected, however if this is a mistake, please upload the log summary and we can re-review.

**Comment by supermario** [comment]
@mrekos it looks like you've submitted lots of PRs that all contain submissions for multiple challenges, can you clarify what this PR is for as the title is unclear?

**Comment by mrekos** [comment]
hi what's the problem


23 Ara 2020 Çar 14:00 tarihinde Mario Rogic <notifications@github.com> şunu
yazdı:

**Comment by mrekos** [comment]
something must have gone wrong. Is it possible to fix this?

29 Ara 2020 Sal 14:31 tarihinde Mario Rogic <notifications@github.com> şunu
yazdı:

**Comment by supermario** [comment]
@mrekos can you please list which challenges you are submitting in this PR?

**Review by mrekos — COMMENTED** [review]
Log file for task B1 available here  >> https://github.com/mrekos/Testnet3-Challenges/blob/B1/Bakers/B1/%20B1%20log%20concordium-testnet-node-eb17f7ef9232124fc45cad5e4976f5cbab559d121cc8c46f334f7fcc975f9760.log

**Comment by cryptovoyagr** [comment]
@mrekos can you please answer @supermario's question as mentioned above? 

"it looks like you've submitted lots of PRs that all contain submissions for multiple challenges, can you clarify what this PR is for as the title is unclear?" 

"@mrekos can you please list which challenges you are submitting in this PR?"

**Comment by mrekos** [comment]
> @mrekos can you please answer @supermario's question as mentioned above?
> 
> "it looks like you've submitted lots of PRs that all contain submissions for multiple challenges, can you clarify what this PR is for as the title is unclear?"
> 
> "@mrekos can you please list which challenges you are submitting in this PR?"

I opened a branch for each task separately from there you can see which file was loaded for which task.

**Comment by supermario** [comment]
@mrekos it appears all the challenges you've submitted in this PR were also submitted individually in other PRs.

So I'm untagging and closing this PR. We'll review your submissions in the other PRs.

**Comment by mrekos** [comment]
Screenshot_20210106_154811_com android chrome
I created separate branches for each task and sent files separately, please review

**Pull request closed without merging**
